pyomeca/biorbd

- binding/matlab/MexS2M_rbdl.cpp
- binding/matlab/S2M_ChangeShapeFactors.cpp
- binding/matlab/S2M_MusclesExcitationDotBuchanan.cpp
- binding/matlab/processArguments.cpp
- include/s2mMuscleStateActualBuchanan.h
- src/s2mMuscleStateActualBuchanan.cpp
> Updated buchanan muscles

- include/RigidBody/Joints.h
- src/RigidBody/Joints.cpp
and changed Vector3d to Node3d in Joints.cpp
> Fixed bug in Angular Momentum calculation

- include/Utils/Rotation.h
- src/Utils/CMakeLists.txt
- src/Utils/Rotation.cpp
Took the trans out and commented a few functions.
> Added Rotation.h and Rotation.cpp + modified CMakeList

- test/binding/Python3/test_binder_python_rigidbody.py
Version for CasADi backend also implemented in case of a future with Travais tests that handle CasADi backend
> Test of ForwardDynamicsConstraintsDirect (Eigen and CasADi backends)

- doc/paper/paper.bib
- doc/paper/paper.md
References fixed:
Eigen: added all authors instead of just "and others"
Kurfess: added DOI
biorbdoptim & biorbd-viz: updated to add URLs by using the bibtex from those repositories
for JOSS Review https://github.com/openjournals/joss-reviews/issues/2562#
> Updated paper.bib to fix some references

- doc/paper/paper.md
> Formatting fixes for citations.

- examples/python3/forwardKinematics.py
- examples/python3/inverseKinematicsKalman.py
A very short PR with modifs for the python examples to comply with the new [bioviz](https://github.com/pyomeca/bioviz) naming and code.
If you prefer to do this yourselves I understand as well :smiley:
> python examples updated for new bioviz

- include/RigidBody/Joints.h
- include/RigidBody/Markers.h
- include/RigidBody/SoftContactNode.h
- include/RigidBody/SoftContactSphere.h
- include/RigidBody/SoftContacts.h
- src/ModelReader.cpp
- src/RigidBody/Joints.cpp
- src/RigidBody/Markers.cpp
- src/RigidBody/SoftContactNode.cpp
- src/RigidBody/SoftContactSphere.cpp
- src/RigidBody/SoftContacts.cpp
- test/test_rigidbody.cpp
muStatic, muDynamic and muViscous need to be added to the .bioMod
> Let's make friction coefficients editable

- include/RigidBody/SoftContactNode.h
- src/RigidBody/SoftContactNode.cpp
- src/RigidBody/SoftContacts.cpp
- test/test_rigidbody.cpp
> ComputeForceAtOrigin available for python

- binding/biorbd.i.in
- include/RigidBody/Contacts.h
- include/RigidBody/Joints.h
- include/RigidBody/NodeSegment.h
- src/RigidBody/Contacts.cpp
- src/RigidBody/Joints.cpp
- src/RigidBody/NodeSegment.cpp
- src/RigidBody/SoftContacts.cpp
- test/models/cubeWithExternalForces.bioMod
- test/models/cubeWithRigidContactsExternalForces.bioMod
- test/models/cubeWithSoftContactsRigidContactsExternalForces.bioMod
- test/testWrapperClass.h
- test/test_rigidbody.cpp
I've stashed the work we did together @pariterre.
I develop some extra functions before. 
I still have trouble with the two functions, I've added. I can't use them though python to verify if it's usable because i can't convert it from swig ...
> Handling inverse dynamics with rigid contact

- include/RigidBody/Contacts.h
- src/ModelReader.cpp
- src/RigidBody/Contacts.cpp
- src/RigidBody/Mesh.cpp
- test/test_rigidbody.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/262)
> Bug fix in AddContact since new RBDL API

- src/ModelReader.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/270)
> possibility to add variables in RT assign

- binding/python3/biorbd_python.i.in
- test/binding/Python3/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/279)
> Added the capability to multiply in python

- src/RigidBody/Contacts.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/282)
> Improved version of ToSpatialVector

- include/RigidBody/Joints.h
- src/RigidBody/Joints.cpp
- test/test_rigidbody.cpp
a PR to get jacobian rotation matrix with the API
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/284)
> Jacobian of segment rotation matrix

- src/Utils/Rotation.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/287)
> added yzy rotation to Rotation.toEulerAngles

- src/RigidBody/Joints.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/290)
> Made better message

- binding/python3/model_creation/__init__.py
- binding/python3/model_creation/rotations.py
- binding/python3/model_creation/segment.py
- binding/python3/model_creation/segment_real.py
- binding/python3/model_creation/translations.py
- examples/python3/modelCreation.py
- test/binding/Python3/test_model_creation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/292)
> Replaced translations/rotations litteral for enums

- include/RigidBody/Joints.h
- src/RigidBody/Joints.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/294)
> Fix computeQdot for bioptim

- src/Muscles/HillDeGrooteType.cpp
- src/Muscles/HillThelenType.cpp
- test/test_muscles.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/295)
> Change velocity normalization for degroote muscle type

- .github/workflows/run_eigen_tests.yml
- environment_casadi.yml
- environment_eigen.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/303)
> Tried Github actions

- binding/python3/model_creation/marker_real.py
- binding/python3/model_creation/segment_coordinate_system_real.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/305)
> Fixed a reference bug that was randomly transposing matrices

- binding/python3/model_creation/segment_coordinate_system_real.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/307)
> Fixed the non working "copy" function on np.array on Linux

- include/RigidBody/Joints.h
- src/RigidBody/Joints.cpp
- test/test_rigidbody.cpp
tested and done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/308)
> [RTR] kinetic and potential energy interfaced with rbdl

- binding/python3/model_creation/segment_coordinate_system_real.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/309)
> Bug from transposing in Python

- binding/python3/model_creation/segment_real.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/310)
> Made Python marker more resilient to the absence of parent name

- binding/python3/rigid_body.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/322)
> Added the capability to slice kalman filter before filtering

- include/RigidBody/Segment.h
- src/RigidBody/Segment.cpp
- test/test_rigidbody.cpp
for symbolic use ?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/327)
> [RTR] set LocalJCS of segments

- binding/python3/__init__.py
- binding/python3/external_forces.py
- test/binding/Python3/test_external_forces.py
We clearly need this. In python to begin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/331)
> external_force_helper

- environment_casadi.yml
- environment_eigen.yml
- include/RigidBody/Segment.h
- src/RigidBody/ExternalForceSet.cpp
- src/RigidBody/Segment.cpp
- test/test_rigidbody.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/335)
> Fixed external forces addInSegmentReferenceFrame for segment not being the first

- binding/python3/rigid_body.py
quickly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/337)
> minor doc of Inverse Kinematics

- include/RigidBody/Segment.h
Just to make sure, We remember #343 
@SamHybz, so it will work for any other segment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/345)
> Extra doc setLocalJCS

- binding/matlab/Matlab_Mesh.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/346)
> Fixed matlab compilation issue

- include/RigidBody/Markers.h
- include/RigidBody/NodeSegment.h
- src/RigidBody/Markers.cpp
- src/RigidBody/NodeSegment.cpp
- test/test_rigidbody.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/347)
> Added a setter for the markers

- .github/workflows/publish_matlab_eigen_binaries.yml
- .github/workflows/run_casadi_tests.yml
- .github/workflows/run_codecoverage.yml
- .github/workflows/run_eigen_tests.yml
- include/RigidBody/Joints.h
@pariterre I don't know if we are allowed this much documentation, but it would be worth mentioning what this function actually computes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/362)
> doc update on Angular Momentum By Segment

- include/Utils/Vector3d.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/biorbd/363)
> Added access to Node info for the markers
